app/Http/Controllers/PublisherController.php, app/Http/Requests/PublisherRequest.php, app/Providers/AppServiceProvider.php, app/Repositories/BaseRepository.php, app/Repositories/PublisherRepository.php, app/Repositories/RepositoryInterface/PublisherRepositoryInterface.php, config/app.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/layouts/admin.blade.php, resources/views/layouts/app.blade.php, resources/views/publishers/add.blade.php, resources/views/publishers/edit.blade.php, resources/views/publishers/view.blade.php, routes/web.php
- Create, Read, Update, Delete Publishers
=> Publishers admin

app/Http/Controllers/UserController.php, app/Http/Middleware/Localization.php, app/Http/Requests/UpdateUserRequest.php, app/Providers/AppServiceProvider.php, app/Repositories/RepositoryInterface/UserRepositoryInterface.php, app/Repositories/UserRepository.php, composer.json, composer.lock, config/app.php, database/migrations/2014_10_12_000000_create_users_table.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/layouts/admin.blade.php, resources/views/user/edit.blade.php, resources/views/user/users.blade.php, resources/views/vendor/pagination/bootstrap-4.blade.php, resources/views/vendor/pagination/default.blade.php, resources/views/vendor/pagination/simple-bootstrap-4.blade.php, routes/web.php, tests/Feature/ExampleTest.php, tests/Unit/ExampleTest.php
=> 30386_curd_users

.gitignore, app/Exports/AuthorExport.php, app/Exports/PublisherExport.php, app/Http/Controllers/AuthorController.php, app/Http/Controllers/PublisherController.php, app/Models/Author.php, app/Models/Publisher.php, app/Repositories/AuthorRepository.php, app/Repositories/PublisherRepository.php, composer.json, composer.lock, config/app.php, config/excel.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/authors/view.blade.php, resources/views/publishers/view.blade.php, routes/web.php
Publishers:
- Search by name
- Export list publisher to excel by query search
=> Export search publisher admin

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/CategoryController.php, app/Http/Controllers/HomeController.php, app/Http/Requests/CreateCategoryRequest.php, app/Libraries/ViewComposers/CategoryComposer.php, app/Models/Category.php, app/Providers/AppServiceProvider.php, app/Providers/ViewServiceProvider.php, app/Repositories/CategoryRepository.php, app/Repositories/RepositoryInterface/CategoryRepositoryInterface.php, composer.json, composer.lock, config/app.php, database/migrations/2020_10_07_080509_create_categories_table.php, database/migrations/2020_10_07_081040_create_authors_table.php, database/seeds/AuthorsTableSeeder.php, database/seeds/CategoriesTableSeeder.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/auth/login.blade.php, resources/views/category/categories.blade.php, resources/views/category/create.blade.php, resources/views/category/edit.blade.php, resources/views/layouts/admin.blade.php, resources/views/layouts/app.blade.php, resources/views/user/edit-user.blade.php, routes/web.php
=> 30389_curd_category

app/Exports/AuthorExport.php, app/Http/Controllers/AuthorController.php, app/Models/Author.php, config/app.php, database/seeds/AuthorsTableSeeder.php, database/seeds/BooksTableSeeder.php, database/seeds/PublishersTableSeeder.php, database/seeds/UsersTableSeeder.php, resources/views/authors/view.blade.php, resources/views/publishers/view.blade.php
- Export list author to excel by query search,Search by name
- Fix seeder
=> 30398_Export list author to excel by query search,Search by name

app/Http/Controllers/CategoryController.php, app/Models/Category.php, app/Repositories/CategoryRepository.php, app/Repositories/RepositoryInterface/CategoryRepositoryInterface.php, config/app.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/category/categories.blade.php
=> 30390_search categories by name

app/Http/Controllers/AuthorController.php, app/Http/Controllers/PublisherController.php, app/Http/Controllers/UserController.php, app/Repositories/AuthorRepository.php, app/Repositories/PublisherRepository.php, app/Repositories/RepositoryInterface/PublisherRepositoryInterface.php, app/Repositories/RepositoryInterface/UserRepositoryInterface.php, app/Repositories/UserRepository.php, config/app.php, database/seeds/AuthorsTableSeeder.php, database/seeds/BooksTableSeeder.php, database/seeds/CategoriesTableSeeder.php, database/seeds/PublishersTableSeeder.php, database/seeds/UsersTableSeeder.php
=> fix seeder and controller

app/Http/Controllers/BookController.php, app/Http/Requests/BorrowRequest.php, app/Models/Borrow.php, app/Providers/AppServiceProvider.php, app/Repositories/BorrowRepository.php, app/Repositories/RepositoryInterface/BorrowRepositoryInterface.php, app/Repositories/UserRepository.php, database/migrations/2020_10_07_090912_create_borrows_table.php, resources/lang/en/main.php, resources/lang/vi/main.php, resources/views/book/detail.blade.php, resources/views/subviews/book-item.blade.php, routes/web.php
=> 30403_borrow_book

app/Http/Controllers/AuthorController.php, app/Models/Author.php, app/Repositories/AuthorRepository.php, resources/lang/en/main.php, resources/lang/vi/main.php, resources/views/authors/detail.blade.php, resources/views/authors/view.blade.php, resources/views/authors/viewAll.blade.php, resources/views/book/detail.blade.php, routes/web.php
- View all Authors
- View details author for user
- Search author with name
=> 30409_view detail author for user

app/Http/Controllers/AuthorController.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/PublisherController.php, app/Models/Publisher.php, app/Repositories/PublisherRepository.php, app/Repositories/RepositoryInterface/PublisherRepositoryInterface.php, config/app.php, database/seeds/BorrowsTableSeeder.php, resources/lang/en/main.php, resources/lang/vi/main.php, resources/views/book/detail.blade.php, resources/views/home.blade.php, resources/views/publishers/detail.blade.php, resources/views/publishers/viewAll.blade.php, routes/web.php
- View all publishers for user
- view detail publisher for user
- Search publisher for user
=> View publisher for user

app/Http/Controllers/HomeController.php, app/Models/Book.php, app/Repositories/BookRepository.php, app/Repositories/RepositoryInterface/BookRepositoryInterface.php, package-lock.json, package.json, resources/views/authors/detail.blade.php, resources/views/authors/viewAll.blade.php, resources/views/book/detail.blade.php, resources/views/home.blade.php, resources/views/publishers/detail.blade.php, resources/views/publishers/viewAll.blade.php
Hiển thị danh sách các sách được like nhiều nhất
=> 31150_favourite_book

app/Http/Controllers/ReviewController.php, app/Models/Review.php, app/Repositories/RepositoryInterface/ReviewRepositoryInterface.php, app/Repositories/ReviewRepository.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/layouts/admin.blade.php, resources/views/reviews/view.blade.php, routes/web.php
=> 31249_manage review book

app/Exports/BookExport.php, app/Http/Controllers/BookController.php, app/Models/Book.php, app/Repositories/BookRepository.php, app/Repositories/RepositoryInterface/BookRepositoryInterface.php, config/app.php, resources/lang/en/admin.php, resources/lang/vi/admin.php, resources/views/book/books.blade.php, routes/web.php
- Search book by key word with category
- Export book to excel by query search
=> 30395_30396_export and search book in admin

resources/views/category/edit.blade.php
=> 30919_fix_edit_category

app/Http/Controllers/BookController.php, app/Models/Category.php, app/Repositories/CategoryRepository.php, app/Repositories/RepositoryInterface/CategoryRepositoryInterface.php, resources/lang/en/main.php, resources/lang/vi/main.php, resources/views/book/category.blade.php, resources/views/book/detail.blade.php, resources/views/layouts/app.blade.php, resources/views/subviews/book-item.blade.php, routes/web.php
=> 30392_show_books_in_category

app/Http/Controllers/AuthorController.php, app/Http/Controllers/BorrowController.php, app/Repositories/BorrowRepository.php, app/Repositories/RepositoryInterface/BorrowRepositoryInterface.php, database/migrations/2020_11_05_152548_drop_note_to_borrows_table.php, resources/views/borrows/view.blade.php
=> update manage request borrow book

app/Http/Middleware/EncryptCookies.php, app/Http/Middleware/TrustProxies.php, app/Models/Book.php, composer.lock, tests/ModelTestCase.php, tests/Unit/Models/BookTest.php
=> Test Book Model

tests/Unit/Models/BorrowTest.php
=> Borrow model test

tests/Unit/Models/TestCategory.php
=> Test Category Model

app/Models/User.php, tests/Unit/Models/UserTest.php
=> Test User Model

resources/views/layouts/admin.blade.php, resources/views/layouts/app.blade.php, webpack.mix.js
=> Notification layout

app/Events/NotificationEvent.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/SendNotification.php, app/Notifications/BorrowNotification.php, composer.json, composer.lock, config/app.php, database/migrations/2020_11_17_013134_create_notifications_table.php, resources/views/layouts/app.blade.php
=> Notification realtime for user

app/Http/Controllers/DashboardController.php, app/Http/Controllers/HomeController.php, resources/lang/vi/admin.php, resources/views/admin.blade.php, resources/views/layouts/admin.blade.php, routes/web.php, webpack.mix.js
Thống kê tài khoản đăng ký theo tháng
=> user chart

app/Http/Controllers/BorrowController.php, app/Http/Controllers/SendNotification.php, config/app.php, resources/lang/en/main.php, resources/lang/vi/admin.php, resources/lang/vi/main.php, resources/views/borrows/view.blade.php, resources/views/layouts/app.blade.php
Gửi thông báo về cho user khi yêu cầu mượn sách được chấp nhận hoặc từ chối
=> Send noti to user

app/Console/Commands/NotiAdminCommand.php, app/Console/Kernel.php, resources/lang/en/main.php, resources/lang/vi/main.php
=> send the number of books in request status to admin

app/Http/Controllers/DashboardController.php, app/Repositories/RepositoryInterface/UserRepositoryInterface.php, app/Repositories/UserRepository.php
Sửa lại biểu đồ thống kê người dùng theo tháng
=> fix logic chart

app/Exceptions/Handler.php, app/Http/Controllers/Api/ReviewController.php, app/Http/Controllers/Api/UserController.php, app/Models/User.php, app/Providers/AuthServiceProvider.php, composer.json, composer.lock, config/app.php, config/auth.php, routes/api.php
- Api đăng nhập/đăng ký/xem thông tin tài khoản
- Api xem/thêm/sửa review sách
=> api review

app/Http/Controllers/UserController.php, resources/lang/vi/main.php, resources/views/layouts/app.blade.php, routes/web.php
Đánh dấu đã đọc cho notification
=> mark as read notification

app/Console/Commands/SendMailCommand.php, app/Console/Kernel.php, app/Notifications/BorrowNotification.php, app/Repositories/BorrowRepository.php, app/Repositories/RepositoryInterface/BorrowRepositoryInterface.php, resources/lang/en/main.php, resources/lang/vi/main.php
Gửi mail và thông báo cho người dùng thứ 6 hàng tuần, báo số ngày quá hạn hoặc thời gian còn lại
=> cronjob noti
